// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCecqft2Aro9hn0p_MaddbAi03OpvOJ1mI',
    appId: '1:391281534032:web:54416e818fe03791241d55',
    messagingSenderId: '391281534032',
    projectId: 'grocer-aaf95',
    authDomain: 'grocer-aaf95.firebaseapp.com',
    storageBucket: 'grocer-aaf95.appspot.com',
    measurementId: 'G-XX31C9V2F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1eV7v9CsFBrRq2s3K3d4s5YUwU3Ct9gw',
    appId: '1:391281534032:android:65d01e32d9489813241d55',
    messagingSenderId: '391281534032',
    projectId: 'grocer-aaf95',
    storageBucket: 'grocer-aaf95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHN_d5CIn5j-C0Kgb0H9Sp6NqlEY7deAw',
    appId: '1:391281534032:ios:90f6723caad5c2a6241d55',
    messagingSenderId: '391281534032',
    projectId: 'grocer-aaf95',
    storageBucket: 'grocer-aaf95.appspot.com',
    iosClientId: '391281534032-nbicni9vp5jfr5bnrpjlf5nie26qm62m.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHN_d5CIn5j-C0Kgb0H9Sp6NqlEY7deAw',
    appId: '1:391281534032:ios:90f6723caad5c2a6241d55',
    messagingSenderId: '391281534032',
    projectId: 'grocer-aaf95',
    storageBucket: 'grocer-aaf95.appspot.com',
    iosClientId: '391281534032-nbicni9vp5jfr5bnrpjlf5nie26qm62m.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocerApp',
  );
}
